Remove verbose parameter from ReduceLROnPlateau
- Remove verbose=True parameter which is not supported in this PyTorch version
- Fixes TypeError: ReduceLROnPlateau.__init__() got an unexpected keyword argument 'verbose'